# Generated by Django 2.2.6 on 2019-11-03 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191103_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to='data_uploads/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'CSV'])], verbose_name='CSV File'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL'),
        ),
    ]
